"""initial_schema

Revision ID: 88dd71e25e25
Revises: 
Create Date: 2026-03-12 18:15:12.864562
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '88dd71e25e25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_table('saves',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('player_entity_id', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_saves_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saves'))
    )
    op.create_index(op.f('ix_saves_scenario_id'), 'saves', ['scenario_id'], unique=False)
    op.create_table('beliefs',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('source_template_id', sa.String(length=160), nullable=True),
    sa.Column('holder_entity_id', sa.String(length=160), nullable=False),
    sa.Column('fact_id', sa.String(length=160), nullable=True),
    sa.Column('belief_key', sa.String(length=200), nullable=False),
    sa.Column('belief_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_beliefs_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_beliefs_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beliefs'))
    )
    op.create_index(op.f('ix_beliefs_fact_id'), 'beliefs', ['fact_id'], unique=False)
    op.create_index(op.f('ix_beliefs_holder_entity_id'), 'beliefs', ['holder_entity_id'], unique=False)
    op.create_index(op.f('ix_beliefs_save_id'), 'beliefs', ['save_id'], unique=False)
    op.create_index(op.f('ix_beliefs_scenario_id'), 'beliefs', ['scenario_id'], unique=False)
    op.create_table('combat_encounters',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('save_id', sa.String(length=120), nullable=False),
    sa.Column('location_entity_id', sa.String(length=160), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'WON', 'LOST', 'ESCAPED', name='encounterstate', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('active_combatant_id', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_combat_encounters_save_id_saves')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_combat_encounters'))
    )
    op.create_index(op.f('ix_combat_encounters_location_entity_id'), 'combat_encounters', ['location_entity_id'], unique=False)
    op.create_index(op.f('ix_combat_encounters_save_id'), 'combat_encounters', ['save_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('source_template_id', sa.String(length=160), nullable=True),
    sa.Column('entity_type', sa.Enum('PLAYER', 'PERSON', 'PLACE', 'ITEM', 'FACTION', 'CREATURE', name='entitytype', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_entity_id', sa.String(length=160), nullable=True),
    sa.Column('faction_entity_id', sa.String(length=160), nullable=True),
    sa.Column('is_player', sa.Boolean(), nullable=False),
    sa.Column('is_hostile', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_entities_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_entities_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_location_entity_id'), 'entities', ['location_entity_id'], unique=False)
    op.create_index(op.f('ix_entities_save_id'), 'entities', ['save_id'], unique=False)
    op.create_index(op.f('ix_entities_scenario_id'), 'entities', ['scenario_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('source_template_id', sa.String(length=160), nullable=True),
    sa.Column('event_type', sa.Enum('SYSTEM', 'DIALOGUE', 'MOVEMENT', 'COMBAT', 'QUEST', 'DISCOVERY', 'SIMULATION', name='eventtype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('actor_entity_id', sa.String(length=160), nullable=True),
    sa.Column('target_entity_id', sa.String(length=160), nullable=True),
    sa.Column('location_entity_id', sa.String(length=160), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_events_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_events_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_save_id'), 'events', ['save_id'], unique=False)
    op.create_index(op.f('ix_events_scenario_id'), 'events', ['scenario_id'], unique=False)
    op.create_table('fact_visibility',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('source_template_id', sa.String(length=160), nullable=True),
    sa.Column('fact_id', sa.String(length=160), nullable=False),
    sa.Column('viewer_entity_id', sa.String(length=160), nullable=True),
    sa.Column('viewer_role', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_fact_visibility_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_fact_visibility_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_visibility'))
    )
    op.create_index(op.f('ix_fact_visibility_fact_id'), 'fact_visibility', ['fact_id'], unique=False)
    op.create_index(op.f('ix_fact_visibility_save_id'), 'fact_visibility', ['save_id'], unique=False)
    op.create_index(op.f('ix_fact_visibility_scenario_id'), 'fact_visibility', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_fact_visibility_viewer_entity_id'), 'fact_visibility', ['viewer_entity_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('source_template_id', sa.String(length=160), nullable=True),
    sa.Column('subject_entity_id', sa.String(length=160), nullable=True),
    sa.Column('fact_key', sa.String(length=200), nullable=False),
    sa.Column('truth_text', sa.Text(), nullable=False),
    sa.Column('truth_value', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_facts_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_facts_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facts'))
    )
    op.create_index(op.f('ix_facts_save_id'), 'facts', ['save_id'], unique=False)
    op.create_index(op.f('ix_facts_scenario_id'), 'facts', ['scenario_id'], unique=False)
    op.create_table('inventories',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('owner_entity_id', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_inventories_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_inventories_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventories'))
    )
    op.create_index(op.f('ix_inventories_owner_entity_id'), 'inventories', ['owner_entity_id'], unique=False)
    op.create_index(op.f('ix_inventories_save_id'), 'inventories', ['save_id'], unique=False)
    op.create_index(op.f('ix_inventories_scenario_id'), 'inventories', ['scenario_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('inventory_id', sa.String(length=160), nullable=False),
    sa.Column('item_entity_id', sa.String(length=160), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_inventory_items_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_inventory_items_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items'))
    )
    op.create_index(op.f('ix_inventory_items_inventory_id'), 'inventory_items', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_entity_id'), 'inventory_items', ['item_entity_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_save_id'), 'inventory_items', ['save_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_scenario_id'), 'inventory_items', ['scenario_id'], unique=False)
    op.create_table('place_connections',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('source_template_id', sa.String(length=160), nullable=True),
    sa.Column('from_place_id', sa.String(length=160), nullable=False),
    sa.Column('to_place_id', sa.String(length=160), nullable=False),
    sa.Column('travel_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_place_connections_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_place_connections_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_connections'))
    )
    op.create_index(op.f('ix_place_connections_from_place_id'), 'place_connections', ['from_place_id'], unique=False)
    op.create_index(op.f('ix_place_connections_save_id'), 'place_connections', ['save_id'], unique=False)
    op.create_index(op.f('ix_place_connections_scenario_id'), 'place_connections', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_place_connections_to_place_id'), 'place_connections', ['to_place_id'], unique=False)
    op.create_table('quest_states',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('quest_id', sa.String(length=160), nullable=False),
    sa.Column('actor_entity_id', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ACTIVE', 'COMPLETED', 'FAILED', name='queststatus', native_enum=False), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_quest_states_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_quest_states_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quest_states'))
    )
    op.create_index(op.f('ix_quest_states_actor_entity_id'), 'quest_states', ['actor_entity_id'], unique=False)
    op.create_index(op.f('ix_quest_states_quest_id'), 'quest_states', ['quest_id'], unique=False)
    op.create_index(op.f('ix_quest_states_save_id'), 'quest_states', ['save_id'], unique=False)
    op.create_index(op.f('ix_quest_states_scenario_id'), 'quest_states', ['scenario_id'], unique=False)
    op.create_table('quests',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('source_template_id', sa.String(length=160), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('giver_entity_id', sa.String(length=160), nullable=True),
    sa.Column('target_entity_id', sa.String(length=160), nullable=True),
    sa.Column('reward_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_quests_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_quests_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quests'))
    )
    op.create_index(op.f('ix_quests_save_id'), 'quests', ['save_id'], unique=False)
    op.create_index(op.f('ix_quests_scenario_id'), 'quests', ['scenario_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('source_template_id', sa.String(length=160), nullable=True),
    sa.Column('source_entity_id', sa.String(length=160), nullable=False),
    sa.Column('target_entity_id', sa.String(length=160), nullable=False),
    sa.Column('attitude', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_relationships_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_relationships_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships'))
    )
    op.create_index(op.f('ix_relationships_save_id'), 'relationships', ['save_id'], unique=False)
    op.create_index(op.f('ix_relationships_scenario_id'), 'relationships', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_relationships_source_entity_id'), 'relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_entity_id'), 'relationships', ['target_entity_id'], unique=False)
    op.create_table('scheduled_events',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('source_template_id', sa.String(length=160), nullable=True),
    sa.Column('event_type', sa.Enum('SYSTEM', 'DIALOGUE', 'MOVEMENT', 'COMBAT', 'QUEST', 'DISCOVERY', 'SIMULATION', name='eventtype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('actor_entity_id', sa.String(length=160), nullable=True),
    sa.Column('target_entity_id', sa.String(length=160), nullable=True),
    sa.Column('location_entity_id', sa.String(length=160), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_scheduled_events_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scheduled_events_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_events'))
    )
    op.create_index(op.f('ix_scheduled_events_save_id'), 'scheduled_events', ['save_id'], unique=False)
    op.create_index(op.f('ix_scheduled_events_scenario_id'), 'scheduled_events', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scheduled_events_scheduled_for'), 'scheduled_events', ['scheduled_for'], unique=False)
    op.create_table('world_clock',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('current_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_world_clock_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_world_clock_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_clock'))
    )
    op.create_index(op.f('ix_world_clock_save_id'), 'world_clock', ['save_id'], unique=False)
    op.create_index(op.f('ix_world_clock_scenario_id'), 'world_clock', ['scenario_id'], unique=False)
    op.create_table('combatants',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('encounter_id', sa.String(length=160), nullable=False),
    sa.Column('entity_id', sa.String(length=160), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('is_defeated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['combat_encounters.id'], name=op.f('fk_combatants_encounter_id_combat_encounters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_combatants'))
    )
    op.create_index(op.f('ix_combatants_encounter_id'), 'combatants', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_combatants_entity_id'), 'combatants', ['entity_id'], unique=False)
    op.create_table('entity_stats',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=True),
    sa.Column('save_id', sa.String(length=120), nullable=True),
    sa.Column('entity_id', sa.String(length=160), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('diplomacy', sa.Integer(), nullable=False),
    sa.Column('survival', sa.Integer(), nullable=False),
    sa.Column('stealth', sa.Integer(), nullable=False),
    sa.Column('melee', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('stamina', sa.Integer(), nullable=False),
    sa.Column('max_stamina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_stats_entity_id_entities')),
    sa.ForeignKeyConstraint(['save_id'], ['saves.id'], name=op.f('fk_entity_stats_save_id_saves')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_entity_stats_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_stats'))
    )
    op.create_index(op.f('ix_entity_stats_entity_id'), 'entity_stats', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_stats_save_id'), 'entity_stats', ['save_id'], unique=False)
    op.create_index(op.f('ix_entity_stats_scenario_id'), 'entity_stats', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_stats_scenario_id'), table_name='entity_stats')
    op.drop_index(op.f('ix_entity_stats_save_id'), table_name='entity_stats')
    op.drop_index(op.f('ix_entity_stats_entity_id'), table_name='entity_stats')
    op.drop_table('entity_stats')
    op.drop_index(op.f('ix_combatants_entity_id'), table_name='combatants')
    op.drop_index(op.f('ix_combatants_encounter_id'), table_name='combatants')
    op.drop_table('combatants')
    op.drop_index(op.f('ix_world_clock_scenario_id'), table_name='world_clock')
    op.drop_index(op.f('ix_world_clock_save_id'), table_name='world_clock')
    op.drop_table('world_clock')
    op.drop_index(op.f('ix_scheduled_events_scheduled_for'), table_name='scheduled_events')
    op.drop_index(op.f('ix_scheduled_events_scenario_id'), table_name='scheduled_events')
    op.drop_index(op.f('ix_scheduled_events_save_id'), table_name='scheduled_events')
    op.drop_table('scheduled_events')
    op.drop_index(op.f('ix_relationships_target_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_scenario_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_save_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_quests_scenario_id'), table_name='quests')
    op.drop_index(op.f('ix_quests_save_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_quest_states_scenario_id'), table_name='quest_states')
    op.drop_index(op.f('ix_quest_states_save_id'), table_name='quest_states')
    op.drop_index(op.f('ix_quest_states_quest_id'), table_name='quest_states')
    op.drop_index(op.f('ix_quest_states_actor_entity_id'), table_name='quest_states')
    op.drop_table('quest_states')
    op.drop_index(op.f('ix_place_connections_to_place_id'), table_name='place_connections')
    op.drop_index(op.f('ix_place_connections_scenario_id'), table_name='place_connections')
    op.drop_index(op.f('ix_place_connections_save_id'), table_name='place_connections')
    op.drop_index(op.f('ix_place_connections_from_place_id'), table_name='place_connections')
    op.drop_table('place_connections')
    op.drop_index(op.f('ix_inventory_items_scenario_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_save_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_entity_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_inventory_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_inventories_scenario_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_save_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_owner_entity_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_facts_scenario_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_save_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_fact_visibility_viewer_entity_id'), table_name='fact_visibility')
    op.drop_index(op.f('ix_fact_visibility_scenario_id'), table_name='fact_visibility')
    op.drop_index(op.f('ix_fact_visibility_save_id'), table_name='fact_visibility')
    op.drop_index(op.f('ix_fact_visibility_fact_id'), table_name='fact_visibility')
    op.drop_table('fact_visibility')
    op.drop_index(op.f('ix_events_scenario_id'), table_name='events')
    op.drop_index(op.f('ix_events_save_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_entities_scenario_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_save_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_location_entity_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_combat_encounters_save_id'), table_name='combat_encounters')
    op.drop_index(op.f('ix_combat_encounters_location_entity_id'), table_name='combat_encounters')
    op.drop_table('combat_encounters')
    op.drop_index(op.f('ix_beliefs_scenario_id'), table_name='beliefs')
    op.drop_index(op.f('ix_beliefs_save_id'), table_name='beliefs')
    op.drop_index(op.f('ix_beliefs_holder_entity_id'), table_name='beliefs')
    op.drop_index(op.f('ix_beliefs_fact_id'), table_name='beliefs')
    op.drop_table('beliefs')
    op.drop_index(op.f('ix_saves_scenario_id'), table_name='saves')
    op.drop_table('saves')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
